In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("HR_Dataset.csv")

In [4]:
df.head()

,EmployeeID,FirstName,LastName,Gender,Age,Department,JobRole,Education,MaritalStatus,Salary,Experience,JoiningDate,PerformanceRating,Attrition,Overtime,WorkMode,State,Manager
0,EMP00001,Nikhil,Gupta,Male,25,Operations,Operations Executive,Bachelor,Single,522098,0,2016-12-13,3,Yes,Yes,Office,Telangana,N. Gupta
1,EMP00002,Rahul,Das,Female,41,Marketing,Marketing Executive,MBA,Married,1116426,17,2015-02-23,5,No,Yes,Office,Telangana,A. Sharma
2,EMP00003,Varun,Reddy,Female,34,HR,HR Executive,Bachelor,Divorced,887052,12,2025-04-21,4,No,No,Hybrid,Kerala,K. Singh
3,EMP00004,Ananya,Yadav,Male,42,Marketing,Digital Marketer,Diploma,Married,1089116,18,2016-10-15,2,No,No,Hybrid,Delhi,A. Sharma
4,EMP00005,Rahul,Naidu,Female,35,IT,QA Engineer,MBA,Divorced,1039993,11,2020-06-28,2,Yes,No,Remote,Maharashtra,S. Reddy

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         5000 non-null   object
 1   FirstName          5000 non-null   object
 2   LastName           5000 non-null   object
 3   Gender             5000 non-null   object
 4   Age                5000 non-null   int64
 5   Department         5000 non-null   object
 6   JobRole            5000 non-null   object
 7   Education          5000 non-null   object
 8   MaritalStatus      5000 non-null   object
 9   Salary             5000 non-null   int64
 10  Experience         5000 non-null   int64
 11  JoiningDate        5000 non-null   object
 12  PerformanceRating  5000 non-null   int64
 13  Attrition          5000 non-null   object
 14  Overtime           5000 non-null   object
 15  WorkMode           5000 non-null   object
 16  State              5000 non-null   object
 17  Manager            5000 non-null   object
dtypes: int64(4), object(14)
memory usage: 703.3+ KB

In [6]:
df.isnull().sum()

EmployeeID           0
FirstName            0
LastName             0
Gender               0
Age                  0
Department           0
JobRole              0
Education            0
MaritalStatus        0
Salary               0
Experience           0
JoiningDate          0
PerformanceRating    0
Attrition            0
Overtime             0
WorkMode             0
State                0
Manager              0
dtype: int64

In [7]:
# Check duplicate rows
df.duplicated().sum()

0

In [8]:
#Check Unique Values

#This helps identify spelling mistakes or inconsistent categories.

for col in ["Department", "Gender", "Education", "MaritalStatus",
            "Attrition", "Overtime", "WorkMode", "State"]:
    print(f"\n{col}")
    print(df[col].unique())

Department
['Operations' 'Marketing' 'HR' 'IT' 'Sales' 'Finance']

Gender
['Male' 'Female']

Education
['Bachelor' 'MBA' 'Diploma' 'Master']

MaritalStatus
['Single' 'Married' 'Divorced']

Attrition
['Yes' 'No']

Overtime
['Yes' 'No']

WorkMode
['Office' 'Hybrid' 'Remote']

State
['Telangana' 'Kerala' 'Delhi' 'Maharashtra' 'Karnataka' 'Tamil Nadu'
 'Andhra Pradesh']

In [9]:
df.dtypes

EmployeeID           object
FirstName            object
LastName             object
Gender               object
Age                   int64
Department           object
JobRole              object
Education            object
MaritalStatus        object
Salary                int64
Experience            int64
JoiningDate          object
PerformanceRating     int64
Attrition            object
Overtime             object
WorkMode             object
State                object
Manager              object
dtype: object

In [10]:
df.describe()
# statistical summary

              Age        Salary   Experience  PerformanceRating
count  5000.00000  5.000000e+03  5000.000000        5000.000000
mean     35.46500  8.913018e+05     9.904800           3.496800
std       6.73521  2.239083e+05     6.060815           1.118857
min      21.00000  4.222150e+05     0.000000           2.000000
25%      30.00000  7.064200e+05     5.000000           2.000000
50%      35.00000  8.903975e+05    10.000000           3.000000
75%      41.00000  1.073303e+06    15.000000           5.000000
max      50.00000  1.399213e+06    20.000000           5.000000

In [11]:
# categorical columns
df.describe(include="object")

,EmployeeID,FirstName,LastName,Gender,Department,JobRole,Education,MaritalStatus,JoiningDate,Attrition,Overtime,WorkMode,State,Manager
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,5000,20,15,2,6,14,4,3,2899,2,2,3,7,6
top,EMP00001,Aditya,Patel,Female,Sales,Financial Analyst,Master,Single,2023-10-28,No,No,Hybrid,Karnataka,R. Mehta
freq,1,280,369,2538,881,480,1289,1675,7,3939,3216,1709,758,896

In [12]:
df["Salary"].describe()

count    5.000000e+03
mean     8.913018e+05
std      2.239083e+05
min      4.222150e+05
25%      7.064200e+05
50%      8.903975e+05
75%      1.073303e+06
max      1.399213e+06
Name: Salary, dtype: float64

In [13]:
#Check Age
df["Age"].describe()

count    5000.00000
mean       35.46500
std         6.73521
min        21.00000
25%        30.00000
50%        35.00000
75%        41.00000
max        50.00000
Name: Age, dtype: float64

In [14]:
# individual Ages 
df[(df["Age"] < 18) | (df["Age"] > 60)]

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Gender, Age, Department, JobRole, Education, MaritalStatus, Salary, Experience, JoiningDate, PerformanceRating, Attrition, Overtime, WorkMode, State, Manager]
Index: []

In [15]:
# create Age  New Column
bins = [20, 30, 40, 50, 60]
labels = ["21-30", "31-40", "41-50", "51-60"]

df["AgeGroup"] = pd.cut(df["Age"], bins=bins, labels=labels)

In [16]:
# salary Band

bins = [0, 500000, 800000, 1200000, 2000000]
labels = ["Low", "Medium", "High", "Very High"]

df["SalaryBand"] = pd.cut(df["Salary"], bins=bins, labels=labels)

In [17]:
# experience level

def experience_level(exp):
    if exp <= 2:
        return "Fresher"
    elif exp <= 5:
        return "Junior"
    elif exp <= 10:
        return "Mid-Level"
    else:
        return "Senior"

df["ExperienceLevel"] = df["Experience"].apply(experience_level)

In [18]:
# convert joing date to date time 
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"], errors="coerce")

In [19]:
# tenure 

today = pd.Timestamp.today()

df["Tenure"] = ((today - df["JoiningDate"]).dt.days / 365).round(1)

In [20]:
# save the cleaned dataset

df.to_csv("HR_Analytics_Cleaned.csv", index=False)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         5000 non-null   object
 1   FirstName          5000 non-null   object
 2   LastName           5000 non-null   object
 3   Gender             5000 non-null   object
 4   Age                5000 non-null   int64
 5   Department         5000 non-null   object
 6   JobRole            5000 non-null   object
 7   Education          5000 non-null   object
 8   MaritalStatus      5000 non-null   object
 9   Salary             5000 non-null   int64
 10  Experience         5000 non-null   int64
 11  JoiningDate        5000 non-null   datetime64[ns]
 12  PerformanceRating  5000 non-null   int64
 13  Attrition          5000 non-null   object
 14  Overtime           5000 non-null   object
 15  WorkMode           5000 non-null   object
 16  State              5000 non-null   object
 17  Manager            5000 non-null   object
 18  AgeGroup           5000 non-null   category
 19  SalaryBand         5000 non-null   category
 20  ExperienceLevel    5000 non-null   object
 21  Tenure             5000 non-null   float64
dtypes: category(2), datetime64[ns](1), float64(1), int64(4), object(14)
memory usage: 791.5+ KB

In [22]:
df.head()

,EmployeeID,FirstName,LastName,Gender,Age,Department,JobRole,Education,MaritalStatus,Salary,...,PerformanceRating,Attrition,Overtime,WorkMode,State,Manager,AgeGroup,SalaryBand,ExperienceLevel,Tenure
0,EMP00001,Nikhil,Gupta,Male,25,Operations,Operations Executive,Bachelor,Single,522098,...,3,Yes,Yes,Office,Telangana,N. Gupta,21-30,Medium,Fresher,9.6
1,EMP00002,Rahul,Das,Female,41,Marketing,Marketing Executive,MBA,Married,1116426,...,5,No,Yes,Office,Telangana,A. Sharma,41-50,High,Senior,11.4
2,EMP00003,Varun,Reddy,Female,34,HR,HR Executive,Bachelor,Divorced,887052,...,4,No,No,Hybrid,Kerala,K. Singh,31-40,High,Senior,1.2
3,EMP00004,Ananya,Yadav,Male,42,Marketing,Digital Marketer,Diploma,Married,1089116,...,2,No,No,Hybrid,Delhi,A. Sharma,41-50,High,Senior,9.7
4,EMP00005,Rahul,Naidu,Female,35,IT,QA Engineer,MBA,Divorced,1039993,...,2,Yes,No,Remote,Maharashtra,S. Reddy,31-40,High,Senior,6.0

# EDA

In [23]:
# employee overview
# Total Employees
print("Total Employees:", len(df))

# Department-wise Employee Count
df["Department"].value_counts()

# Gender Distribution
df["Gender"].value_counts()

# Work Mode Distribution
df["WorkMode"].value_counts()

Total Employees: 5000

WorkMode
Hybrid    1709
Office    1672
Remote    1619
Name: count, dtype: int64

### Salary Analysis

In [24]:
# avg salary
df["Salary"].mean()

891301.76

In [25]:
# Highest Salary
df["Salary"].max()

1399213

In [26]:
# lowest salary 
df["Salary"].min()

422215

In [27]:
# salary by dept
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
IT            1.011286e+06
Finance       9.577772e+05
Operations    8.677021e+05
Sales         8.623924e+05
Marketing     8.294972e+05
HR            8.156149e+05
Name: Salary, dtype: float64

In [28]:
# Attrition Count
df["Attrition"].value_counts()

# Attrition Rate
(df["Attrition"] == "Yes").mean() * 100

21.22

In [29]:
# Department-wise Attrition:

df.groupby("Department")["Attrition"].value_counts()

Department  Attrition
Finance     No           692
            Yes          178
HR          No           620
            Yes          168
IT          No           653
            Yes          153
Marketing   No           631
            Yes          164
Operations  No           654
            Yes          206
Sales       No           689
            Yes          192
Name: count, dtype: int64

In [30]:
# Performance Analysis
# Average Performance Rating
df["PerformanceRating"].mean()

3.4968

In [31]:
# Department-wise Performance
df.groupby("Department")["PerformanceRating"].mean()

Department
Finance       3.543678
HR            3.483503
IT            3.540943
Marketing     3.471698
Operations    3.472093
Sales         3.468785
Name: PerformanceRating, dtype: float64

In [32]:
#Experience Analysis
# Average Experience
df["Experience"].mean()

9.9048

In [33]:
# Experience Level Count
df["ExperienceLevel"].value_counts()

ExperienceLevel
Senior       2372
Mid-Level    1157
Junior        763
Fresher       708
Name: count, dtype: int64

In [34]:
# Age Analysis

#avg age
df["Age"].mean()

35.465

In [35]:
# Age group Distribution
df["AgeGroup"].value_counts()

AgeGroup
31-40    2360
21-30    1327
41-50    1313
51-60       0
Name: count, dtype: int64

In [36]:
# over time Analysis

df["Overtime"].value_counts()

Overtime
No     3216
Yes    1784
Name: count, dtype: int64

In [37]:
# overtime vs Attrition 

pd.crosstab(df["Overtime"], df["Attrition"])

Attrition    No  Yes
Overtime
No         2633  583
Yes        1306  478

In [38]:
# State Analysis
df["State"].value_counts()

State
Karnataka         758
Maharashtra       723
Tamil Nadu        723
Telangana         713
Delhi             711
Kerala            698
Andhra Pradesh    674
Name: count, dtype: int64

In [39]:
# Hiring Trend
df["JoiningYear"] = df["JoiningDate"].dt.year

df["JoiningYear"].value_counts().sort_index()

JoiningYear
2015    384
2016    469
2017    440
2018    422
2019    430
2020    431
2021    414
2022    412
2023    481
2024    456
2025    441
2026    220
Name: count, dtype: int64

In [40]:
# correlation

df[["Age","Salary","Experience","PerformanceRating","Tenure"]].corr()

                        Age    Salary  Experience  PerformanceRating    Tenure
Age                1.000000  0.855213    0.903990           0.017970 -0.019671
Salary             0.855213  1.000000    0.946727           0.025522 -0.020481
Experience         0.903990  0.946727    1.000000           0.020752 -0.017004
PerformanceRating  0.017970  0.025522    0.020752           1.000000 -0.004001
Tenure            -0.019671 -0.020481   -0.017004          -0.004001  1.000000

In [41]:
# save the final set

df.to_csv("HR_Analytics_Final.csv", index=False)

In [42]:
df.to_excel("HR_Analytics_Final.xlsx", index=False)

In [43]:
df["JoiningDate"] = df["JoiningDate"].dt.strftime("%Y-%m-%d")

In [44]:
df.head()

,EmployeeID,FirstName,LastName,Gender,Age,Department,JobRole,Education,MaritalStatus,Salary,...,Attrition,Overtime,WorkMode,State,Manager,AgeGroup,SalaryBand,ExperienceLevel,Tenure,JoiningYear
0,EMP00001,Nikhil,Gupta,Male,25,Operations,Operations Executive,Bachelor,Single,522098,...,Yes,Yes,Office,Telangana,N. Gupta,21-30,Medium,Fresher,9.6,2016
1,EMP00002,Rahul,Das,Female,41,Marketing,Marketing Executive,MBA,Married,1116426,...,No,Yes,Office,Telangana,A. Sharma,41-50,High,Senior,11.4,2015
2,EMP00003,Varun,Reddy,Female,34,HR,HR Executive,Bachelor,Divorced,887052,...,No,No,Hybrid,Kerala,K. Singh,31-40,High,Senior,1.2,2025
3,EMP00004,Ananya,Yadav,Male,42,Marketing,Digital Marketer,Diploma,Married,1089116,...,No,No,Hybrid,Delhi,A. Sharma,41-50,High,Senior,9.7,2016
4,EMP00005,Rahul,Naidu,Female,35,IT,QA Engineer,MBA,Divorced,1039993,...,Yes,No,Remote,Maharashtra,S. Reddy,31-40,High,Senior,6.0,2020

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         5000 non-null   object
 1   FirstName          5000 non-null   object
 2   LastName           5000 non-null   object
 3   Gender             5000 non-null   object
 4   Age                5000 non-null   int64
 5   Department         5000 non-null   object
 6   JobRole            5000 non-null   object
 7   Education          5000 non-null   object
 8   MaritalStatus      5000 non-null   object
 9   Salary             5000 non-null   int64
 10  Experience         5000 non-null   int64
 11  JoiningDate        5000 non-null   object
 12  PerformanceRating  5000 non-null   int64
 13  Attrition          5000 non-null   object
 14  Overtime           5000 non-null   object
 15  WorkMode           5000 non-null   object
 16  State              5000 non-null   object
 17  Manager            5000 non-null   object
 18  AgeGroup           5000 non-null   category
 19  SalaryBand         5000 non-null   category
 20  ExperienceLevel    5000 non-null   object
 21  Tenure             5000 non-null   float64
 22  JoiningYear        5000 non-null   int32
dtypes: category(2), float64(1), int32(1), int64(4), object(15)
memory usage: 811.1+ KB

In [46]:
df["JoiningDate"].head()

0    2016-12-13
1    2015-02-23
2    2025-04-21
3    2016-10-15
4    2020-06-28
Name: JoiningDate, dtype: object

In [47]:
df.to_csv("HR_Analytics_Final.csv", index=False)

In [48]:
df.to_excel("HR_Analytics_Final.xlsx", index=False)